### ISSUE TITLE
Summary doesn't include the table

### ISSUE THREAD

**Issue by elinw** [danielmarcelino/SciencesPo#7]
I don't think that summary is working as it is intended. If I run the sample code from the documents `summary(mytab[['object']])`  is the same as `mytab` in that it includes just the summary statistics. However there is seemingly no way to get the table itself. 

Also `summary(mytab)` just gives

        Length            Class         Mode
       summary 7      summary.table list
       object  5      assocstats    list

which doesn't seem like what you are building in the code.

**Comment by danielmarcelino** [comment]
This is a know issue and have been there for a while since I had to place the `summary.crosstable` function inside of the `crosstable`. I will come back soon to develop the package for the next release, so I hope to fix it at once and also provide output in latex. Thanks for pointing it out.

**Comment by danielmarcelino** [comment]
From now on, the `crosstable` function does not print `vcd` independence tests right below the table output. I'll add on demand each test e.g `chisq=TRUE`, `phi=TRUE` etc, like in the `gmodels` CrossTable function; so the user can have much more control to what to display below the table. The next release will provide only the `chisq`  test, but the list of tests will grow with time.
